name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/scripts/**'
      - '.github/workflows/build_push.yml'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 15
  IS_PR_CHECK: false

jobs:
  prepare:
    permissions:
      contents: write
    name: Prepare job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      latestCommitMessage: ${{ steps.set-env.outputs.LATEST_COMMIT_MESSAGE }}
      matrix: ${{ steps.generate-matrices.outputs.matrix }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
      skipBump: ${{ steps.set-env.outputs.SKIP_BUMP }}
    steps:
      - name: Checkout ${{ github.ref_name }} branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set env
        id: set-env
        env:
          HEAD_SHA: ${{ github.sha }}
        run: |
          LATEST_COMMIT_MESSAGE=$(git log -1 --pretty=%B "$HEAD_SHA")
          echo "LATEST_COMMIT_MESSAGE<<{delimiter}
          $LATEST_COMMIT_MESSAGE

          Built on commit: $HEAD_SHA
          {delimiter}" >> $GITHUB_OUTPUT

          skip_bump=false
          skip_build=false
          case "$LATEST_COMMIT_MESSAGE" in
            "[skip yuzono ci]"*)
              skip_bump=true
              skip_build=true
              ;;
            "[skip bumping version]"*)
              skip_bump=true
              ;;
          esac
          echo "SKIP_BUMP=$skip_bump" >> $GITHUB_OUTPUT
          echo "SKIP_BUILD=$skip_build" >> $GITHUB_OUTPUT

      - name: Get last successful CI commit
        uses: nrwl/nx-set-shas@v5
        with:
          main-branch-name: ${{ github.ref_name }}
          fallback-sha: 4b825dc642cb6eb9a060e54bf8d69288fbee4904

      - id: generate-matrices
        name: Create output matrices
        env:
          SKIP_BUILD: ${{ steps.set-env.outputs.SKIP_BUILD }}
        run: |
          if [ "$SKIP_BUILD" = "true" ]; then
            echo 'matrix={"chunk":[]}' >> $GITHUB_OUTPUT
            echo 'delete=[]' >> $GITHUB_OUTPUT
          else
            python ./.github/scripts/generate-build-matrices.py "$NX_BASE" Release
          fi

  build:
    name: Build extensions (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout ${{ github.ref_name }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
        run: |
          ./gradlew $MODULES -x spotlessKotlinCheck

      - name: Upload APKs (${{ matrix.chunk.number }})
        uses: actions/upload-artifact@v4
        with:
          name: "individual-apks-${{ matrix.chunk.number }}"
          path: "**/*.apk"
          retention-days: 1

  publish:
    name: Publish extension repo
    needs: [prepare, build]
    if: >-
      !cancelled()
      && needs.prepare.result == 'success'
      && (needs.build.result == 'success' || needs.build.result == 'skipped')
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/apk-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Checkout ${{ github.ref_name }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          path: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Create repo artifacts
        run: |
          cd ${{ github.ref_name }}
          python ./.github/scripts/move-built-apks.py
          INSPECTOR_LINK="$(curl -s "https://api.github.com/repos/komikku-app/aniyomi-extensions-inspector/releases/latest" | jq -r '.assets[0].browser_download_url')"
          curl -L "$INSPECTOR_LINK" -o ./Inspector.jar
          java -jar ./Inspector.jar "repo/apk" "output.json" "tmp"
          python ./.github/scripts/create-repo.py

      - name: Checkout repo branch
        uses: actions/checkout@v4
        with:
          ref: repo
          path: repo
          fetch-depth: 0

      - name: Merge repo
        env:
          DELETE: ${{ needs.prepare.outputs.delete }}
        run: |
          cd repo
          python ../${{ github.ref_name }}/.github/scripts/merge-repo.py "$DELETE" '${{ github.ref_name }}/repo'

      - name: Deploy repo
        uses: EndBug/add-and-commit@v11
        with:
          message: "${{ needs.prepare.outputs.latestCommitMessage }}"
          cwd: "./repo"
